name: Export

on:
  push:
  pull_request:

jobs:
  export:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inti-cmnb/kicad_auto_test:nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run kibot
        run: kibot -vvv
      - name: Archive Gerber ZIP
        uses: actions/upload-artifact@v2
        with:
          name: jlc
          path: JLCPCB/uno-vik-adapter-JLCPCB.zip
      - name: Archive Positions/BOM
        uses: actions/upload-artifact@v2
        with:
          name: jlc
          path: uno-vik-adapter_*jlc.csv
